### PR TITLE
Parse quote identifiers

### LINKED ISSUE #23: Panic when parsing quoted identifiers
SMTLIB allows for defining identifiers with restricted characters by wrapping them in `|`: `|foo::bar@10|`. However, the crate fails to parse such identifiers:
```rust
use easy_smt::{ContextBuilder, Response};

fn main() -> std::io::Result<()> {
    // Create a new context, backed by a Z3 subprocess.
    let mut ctx = ContextBuilder::new()
        .solver("z3", ["-smt2", "-in"])
        .replay_file(Some(std::fs::File::create("replay.smt2")?))
        .build()?;

    // Declare `x` and `y` variables that are bitvectors of width 32.
    let x = ctx.declare_const("|x::10|", ctx.int_sort())?;

    // Assert that `x * y = 18`.
    ctx.assert(ctx.eq(x, ctx.numeral(10)))?;

    // Check whether the assertions are satisfiable. They should be in this example.
    assert_eq!(ctx.check()?, Response::Sat);

    // Print the solution!
    let solution = ctx.get_value(vec![x])?;
    for (variable, value) in solution {
        println!("{} = {}", ctx.display(variable), ctx.display(value));
    }

    Ok(())
}
```

The expected output would be printing:
```
|x::10| = <value>
```

Unfortunately, we get:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `5`', /Users/rachitnigam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/easy-smt-0.2.0/src/context.rs:444:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running the `replay.smt2` file, we get the right answer:
```
% z3 -smt2 replay.smt2 
success
success
success
success
sat
((|x::10| 10))
```

It looks like we hit an [`assert!` in implementation of `get_value`](https://github.com/elliottt/easy-smt/blob/main/src/context.rs#L444) which is probably triggered because the parser doesn't handle quoted identifiers correctly.

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #23.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Just tagging @elliottt for a review

File: src/sexpr.rs [hunk 1]
```diff
@@ -393,6 +406,10 @@ impl<'a> Lexer<'a> {
             break;
         }
 
+        // NOTE(rachitnigam): Not sure if this is the best way to signal an
+        // error in the lexer.
+        assert!(!quoted, "unterminated | in symbol");
```
Comment (elliottt) [inline src/sexpr.rs:411]: Good point! We didn't really have any parse errors before, given how permissive the symbol parsing was, so it would be nice to revisit that in a follow-up PR.

File: src/sexpr.rs [hunk 2]
```diff
@@ -377,12 +377,25 @@ impl<'a> Lexer<'a> {
...
-                if c.is_alphabetic() || c.is_numeric() || "~!@$%^&*_-+=<>.?/".contains(*c) {
+                if quoted && *c != '|' {
+                    // If we're in a quoted context, treat this as one identifier.
+                    self.indices.next();
+                    continue;
+                } else if *c == '|' {
+                    // If we see a quote, toggle the quoted flag.
+                    quoted = !quoted;
+                    self.indices.next();
+                    continue;
```
Comment (elliottt) [inline src/sexpr.rs:397]: Is it possible to escape the quotes? If not, this state machine seems reasonable to me 👍

**Review by elliottt — APPROVED** [review]
This looks good to me, thanks for fixing this!

File: src/sexpr.rs (hunk 2 above)
Comment (rachitnigam) [reply src/sexpr.rs:397]: I don't *think* so? The quoted identifiers are specified as not containing `|` so I imagine you can't escape but I am also new to the feature.

File: src/sexpr.rs (hunk 1 above)
Comment (rachitnigam) [reply src/sexpr.rs:411]: Yeah, some simple API to report the errors would be useful!

**Comment by rachitnigam** [comment]
Can we do a new release once this is merged?
