### PR TITLE
Pass-through single-element arguments to variadic constructors

### LINKED ISSUE #8: Request: `and_many` etc to work on single-element vectors
Right now, if you pass a single-element vector to `and_many`, like:
```
s.and_many(vec![s.true_()]);
```
It fails with:
```
thread '<unnamed>' panicked at 'assertion failed: args.len() >= 3', /Users/avh/.cargo/git/checkouts/easy-smt-fe5539f05befcda8/18df991/src/context.rs:631:5
```

A common pattern is to dynamically build a list of expressions then call one of these variadic helpers, so it would be nice to not have to special case on a single element each time. The library could instead return the single value (at least for the helpers where that is correct).

### PR DESCRIPTION
**Pull request by elliottt**
Pass through the expression given when variadic constructors like `and_many` are called with an iterator that yields a single element. Those constructors will still panic if given no arguments, but they don't require `2` anymore.

Fixes #8

### CODE REVIEW

File: src/context.rs [hunk 1]
```diff
@@ -803,3 +812,29 @@ mod private {
...
+    }
+
+    #[test]
+    fn test_variadic_ops() {
+        let ctx = ContextBuilder::new().build().unwrap();
+
+        // As all variadic operators are generated by the `variadic!` macro above, we really only need
+        // to pick one to test.
+        check_expr!(ctx, ctx.imp_many([ctx.true_()]), "true");
+        check_expr!(
```
Comment (elliottt) [inline src/context.rs:834]: I'm definitely open to changing this to the whole set of `*_many` ops. My feeling was that this made sense as a default behavior for all of them, but there might be a case I'm not thinking about.

File: src/context.rs [hunk 2]
```diff
@@ -8,9 +8,18 @@ use std::{ffi, io};
 macro_rules! variadic {
     ($name:ident, $op:ident) => {
         pub fn $name<I: IntoIterator<Item = SExpr>>(&self, items: I) -> SExpr {
-            let args: Vec<_> = std::iter::once(self.atoms.$op).chain(items).collect();
-            assert!(args.len() >= 3);
-            self.list(args)
+            let mut iter = items.into_iter().peekable();
+            let first = iter.next().expect("At least one argument is expected");
```
Comment (fitzgen) [inline src/context.rs:12]: FWIW, `all([]) == true` and `any([]) == false`. Not sure whether we want to actually implement that however...

**Review by fitzgen — APPROVED** [review]
LGTM, something to think about below, but I think we can merge this as-is and make any further changes in follow up PRs.

File: src/context.rs (hunk 2 above)
Comment (elliottt) [reply src/context.rs:12]: That's a great point. We could add another case to `variadic!` to handle empty inputs when there's a known reasonable value.

Comment (fitzgen) [reply src/context.rs:12]: @avanhatt would you find ^ useful?

Comment (avanhatt) [reply src/context.rs:12]: Hm, I have less of a strong opinion on the empty case! It would save me a bit of special casing, but as long as I don't need separate special cases for 0 vs 1 vs. many elements, I could go either way.
